version: "3.8"
services:
 ansible-runner:
  container_name: ansible-runner
  image: jkaninda/ansible-runner:latest
  privileged: true
  command: sleep 1d
  restart: unless-stopped
  volumes:
    - ./master:/etc/ansible/
  networks:
   - ansible
networks:
 ansible:
  external: false
  name: ansible