name: Build
on:
  push:
    branches:
      - main

env:
  BUILDKIT_IMAGE: jkaninda/ansible-runner
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - 
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - 
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          file: "./Dockerfile"
          push: true
          tags: |
           "${{env.BUILDKIT_IMAGE}}:8.7"
           "${{env.BUILDKIT_IMAGE}}:latest"
     